name: basic_api
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  grpc: '>=1.0.2'
  protobuf: '>=0.13.11'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
